Log FW Update error

diff --git a/platform/mellanox/mlnx-fw-upgrade.j2 b/platform/mellanox/mlnx-fw-upgrade.j2
--- a/platform/mellanox/mlnx-fw-upgrade.j2
+++ b/platform/mellanox/mlnx-fw-upgrade.j2
@@ -186,6 +186,23 @@ function RunCmd() {
     fi
 }
 
+function RunFwUpdateCmd() {
+    local ERROR_CODE="${EXIT_SUCCESS}"
+    local COMMAND="${BURN_CMD} $@"
+
+    if [[ "${VERBOSE_LEVEL}" -eq "${VERBOSE_MAX}" ]]; then
+            output=$(eval "${COMMAND}")
+    else
+            output=$(eval "${COMMAND}") >/dev/null 2>&1
+    fi
+
+    ERROR_CODE="$?"
+    if [[ "${ERROR_CODE}" != "${EXIT_SUCCESS}" ]]; then
+        failure_msg=${output#*Fail : }
+        ExitFailure "FW Update command failed: ${COMMAND} with error:" ${failure_msg}
+    fi
+}
+
 function UpgradeFW() {
     local -r _FS_MOUNTPOINT="$1"
 
@@ -229,9 +246,9 @@ function UpgradeFW() {
         local -r _MST_DEVICE="$(GetMstDevice)"
         if [[ "${_MST_DEVICE}" = "${UNKN_MST}" ]]; then
             LogWarning "could not find fastest mst device, using default device"
-            RunCmd "${BURN_CMD} -i ${_FW_FILE}"
+            RunFwUpdateCmd "-i ${_FW_FILE}"
         else
-            RunCmd "${BURN_CMD} -d ${_MST_DEVICE} -i ${_FW_FILE}"
+            RunFwUpdateCmd "-d ${_MST_DEVICE} -i ${_FW_FILE}"
         fi
     fi
 }
